---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-products
  labels:
    app: spring-boot-products
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-products
  labels:
    app: spring-boot-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-products
  template:
    metadata:
      labels:
        app: spring-boot-products
    spec:
      runtimeClassName: kontain
      containers:
      - name: spring-boot-products
        image: kontainguide/spring-boot-products:1.0
        ports:
        - containerPort: 8080