# FROM python:3.8-slim AS build
# WORKDIR /opt/src/app

# RUN python3 -m venv /opt/venv
# # Make sure we use the virtualenv:
# ENV PATH="/opt/venv/bin:$PATH"
 
# ADD . /opt/src/
# RUN pip install -r /opt/src/requirements.txt

# FROM kontainapp/runenv-python-3.8:v0.9.1 as release
# COPY --from=build /opt/venv /opt/venv
# ADD app/main.py /opt/src/app/
# ENV PATH="/opt/venv/bin:$PATH"
# WORKDIR /opt/src/app
 
# EXPOSE 5000
# CMD ["python", "main.py"]
# # CMD . /opt/venv/bin/activate && exec python main.py

FROM python:3.9.7 as build
WORKDIR /opt/src
COPY ./requirements.txt /opt/src/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /opt/src/requirements.txt

# runenv-python is at 3.9.7
FROM kontainapp/runenv-python as release
COPY --from=build /usr/local/bin/uvicorn  /usr/local/bin/uvicorn
COPY --from=build /usr/local/lib/python3.9/*  /usr/local/lib/python3.9/

ADD app/__init__.py /opt/src/app/
ADD app/main.py /opt/src/app/

EXPOSE 8080
# CMD ["python", "main.py"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
