---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-hello
  labels:
    app: fastapi-hello
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: fastapi-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello
  labels:
    app: fastapi-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-hello
  template:
    metadata:
      labels:
        app: fastapi-hello
    spec:
      runtimeClassName: kontain
      containers:
      - name: fastapi-hello
        image: kontainguide/fastapi-hello:1.0
        ports:
        - containerPort: 8080
