---
apiVersion: v1
kind: Service
metadata:
  name: blog-posts-api
  labels:
    app: blog-posts-api
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: blog-posts-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-posts-api
  labels:
    app: blog-posts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-posts-api
  template:
    metadata:
      labels:
        app: blog-posts-api
    spec:
      runtimeClassName: kontain
      containers:
      - name: blog-posts-api
        image: kontainguide/blog-posts-api:1.0
        ports:
        - containerPort: 8080