---
apiVersion: v1
kind: Service
metadata:
  name: py-flask-hello
  labels:
    app: py-flask-hello
spec:
  type: ClusterIP 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: py-flask-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-flask-hello
  labels:
    app: py-flask-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-flask-hello
  template:
    metadata:
      labels:
        app: py-flask-hello
    spec:
      runtimeClassName: kontain
      containers:
      - name: py-flask-hello
        image: kontainguide/py-flask-hello:1.0
        ports:
        - containerPort: 5000
