---
apiVersion: v1
kind: Service
metadata:
  name: golang-http-hello
  labels:
    app: golang-http-hello
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: golang-http-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-hello
  labels:
    app: golang-http-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-http-hello
  template:
    metadata:
      labels:
        app: golang-http-hello
    spec:
      runtimeClassName: kontain
      containers:
      - name: golang-http-hello
        image: docker.io/kontainguide/golang-http-hello:1.0
        ports:
        - containerPort: 8080