apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-kontain
spec:
  template:
    spec:
      runtimeClassName: kontain
      containers:
        - image: docker.io/kontainguide/golang-http-hello:1.0 # gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "knative"
  traffic:
    - latestRevision: true
      percent: 50
    - latestRevision: false
      percent: 50
      revisionName: hello-kontain-00001
