apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-kontain-spring-boot
spec:
  template:
    spec:
      runtimeClassName: kontain
      containers:
        - image: kontainguide/spring-boot-hello:1.0
          ports:
            - containerPort: 8080
