install-km:
	helm install kontain kontain --set install_type=km

install-km-dry-run:
	helm install kontain kontain --set install_type=km --dry-run

install-kkm:
	helm install kontain kontain --set install_type=km

install-kkm-dry-run:
	helm install kontain kontain --set install_type=km --dry-run

install-km-crio:
	helm install kontain kontain --set install_type=km-crio

install-km-crio-dry-run:
	helm install kontain kontain --set install_type=km-crio --dry-run

install-k3s:
	helm install kontain kontain --set install_type=k3s

install-k3s:
	helm install kontain kontain --set install_type=k3s --dry-run

package:
	helm package kontain

uninstall:
	helm uninstall kontain