---
apiVersion: v1
kind: Service
metadata:
  name: kontain-http-uname
  labels:
    app: kontain-http-uname
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kontain-http-uname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontain-http-uname
  labels:
    app: kontain-http-uname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kontain-http-uname
  template:
    metadata:
      labels:
        app: kontain-http-uname
    spec:
      runtimeClassName: kontain
      containers:
      - name: kontain-http-uname
        image: docker.io/kontainguide/kontain-http-uname:1.0
        ports:
        - containerPort: 8080
