---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
  labels:
    app: node-hello-world
spec:
  type: ClusterIP 
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: node-hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
  labels:
    app: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      runtimeClassName: kontain
      containers:
      - name: node-hello-world
        image: kontainguide/node-hello-world:1.0
        ports:
        - containerPort: 3000