apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-kontain
spec:
  template:
    spec:
      containers:
        - image: kontainguide/golang-http-hello:1.0 # gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
