apiVersion: v1
data:
  {{- if eq .Values.install_type "km-crio" }}
  entrypoint.sh:  {{ .Values.km_crio_install_config.kontain_install_entrypoint | toYaml | indent 4 }}
  {{- else }}
  entrypoint.sh:  {{ .Values.km_install_config.kontain_install_entrypoint | toYaml | indent 4 }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app: kontain-init
  name: kontain-install-entrypoint
  namespace: kube-system