apiVersion: v1
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash

    set -x
    set -euo pipefail

    ROOT_MOUNT_DIR="${ROOT_MOUNT_DIR:-/root}"

    echo "logging the instance this is running on for debugging purposes"
    chroot ${ROOT_MOUNT_DIR} echo running on $(hostname)

    CONTAINERD_CFG_DIR="${CONTAINERD_CFG_DIR:-/etc/containerd}"

    source /scripts-lib/kontain_install_lib.sh

    echo "Installing Kontain Runtime Artifacts (KM & KRUN)"
    install_kontain_artifacts

    echo "Add Kontain Runtime to containerd configuration"
    # check to see if its a normal k8s distribution or k3s
    if [ -f /etc/containerd/config.toml ]; then
      echo "its a regular k8s install"
      CONTAINERD_CFG_DIR="${CONTAINERD_CFG_DIR:-/etc/containerd}"
      containerd_conf_file="/etc/containerd/config.toml"
    elif [ -f /etc/containerd/config-kops.toml ]; then
      echo "its a kops cluster install"
      CONTAINERD_CFG_DIR="${CONTAINERD_CFG_DIR:-/etc/containerd}"
      containerd_conf_file="${CONTAINERD_CFG_DIR}/config-kops.toml"
    elif [ -d /root/var/lib/rancher/k3s/agent ]; then
      echo "its a k3s install"
      CONTAINERD_CFG_DIR="${K3S_CONTAINERD_DIR:/root/var/lib/rancher/k3s/agent/etc/containerd}"
      cp "${CONTAINERD_CFG_DIR}/config.toml" "${CONTAINERD_CFG_DIR}/config.toml.tmpl"
      containerd_conf_file="${CONTAINERD_CFG_DIR}/config.toml.tmpl"
    fi

    runtime="krun"
    configuration="configuration"
    pluginid=cri
    if grep -q "version = 2\>" ${containerd_conf_file}; then
      pluginid=\"io.containerd.grpc.v1.cri\"
    fi

    runtime_table="plugins.${pluginid}.containerd.runtimes.$runtime"
    runtime_type="io.containerd.${runtime}.v2"
    options_table="${runtime_table}.options"
    config_path=""
    if grep -q "\[$runtime_table\]" ${containerd_conf_file}; then
        echo "Configuration exists for ${runtime_table}, overwriting"
        sed -i "/\[$runtime_table\]/,+1s#runtime_type.*#runtime_type = \"${runtime_type}\"#" $containerd_conf_file
    else
        cat <<-EOT | tee -a $containerd_conf_file
          [$runtime_table]
          runtime_type = "${runtime_type}"
          privileged_without_host_devices = true
          pod_annotations = ["app.kontain.*"]
    EOT
    fi

    [ -c /root/dev/kvm ] && chmod 666 /root/dev/kvm

    echo "restart containerd"
    systemctl daemon-reload
    systemctl restart containerd

    sleep infinity
kind: ConfigMap
metadata:
  labels:
    app: kontain-init
  name: kontain-install-entrypoint
  namespace: kube-system
---
apiVersion: v1
data:
  kontain_install_lib.sh: |-
    #!/usr/bin/env bash
    TAG=${1:-$(curl -L -s https://raw.githubusercontent.com/kontainapp/km/current/km-releases/current_release.txt)}
    KONTAIN_RELEASE_URL="https://github.com/kontainapp/km/releases/download/${TAG}/kontain_bin.tar.gz"
    echo "KONTAIN_RELEASE_URL is: ${KONTAIN_RELEASE_URL}"

    function install_kontain_artifacts() {
      ROOT_MOUNT_DIR="${ROOT_MOUNT_DIR:-/root}"

      source /$ROOT_MOUNT_DIR/etc/os-release
      if [[ "$ID" == "amzn" ]]; then
        echo "we are running this daemonset on ${ID}"
        chroot ${ROOT_MOUNT_DIR} rm /var/lib/rpm/__db*
        chroot ${ROOT_MOUNT_DIR} yum update -y
        sleep 2
        chroot ${ROOT_MOUNT_DIR} yum install  -y kernel-devel-$(uname -r)
        sleep 2
        chroot ${ROOT_MOUNT_DIR} ls /lib/modules
      elif [[ "$ID" == "ubuntu" ]]; then
        echo "we are running this daemonset on ${ID}"
      fi;

      echo "Install Kontain Runtime Artifacts (KM & KRUN)"

      mkdir -p ${ROOT_MOUNT_DIR}/kontain-artifacts
      curl -Ls "${KONTAIN_RELEASE_URL}" | tar -xzf - -C ${ROOT_MOUNT_DIR}/kontain-artifacts

      mkdir -p ${ROOT_MOUNT_DIR}/opt/kontain/bin

      cp ${ROOT_MOUNT_DIR}/kontain-artifacts/km/km ${ROOT_MOUNT_DIR}/opt/kontain/bin/km
      chmod +x ${ROOT_MOUNT_DIR}/opt/kontain/bin/km

      cp ${ROOT_MOUNT_DIR}/kontain-artifacts/container-runtime/krun ${ROOT_MOUNT_DIR}/opt/kontain/bin/krun
      chmod +x ${ROOT_MOUNT_DIR}/opt/kontain/bin/krun

      mkdir -p ${ROOT_MOUNT_DIR}/opt/kontain/shim
      cp ${ROOT_MOUNT_DIR}/kontain-artifacts/cloud/k8s/deploy/shim/containerd-shim-krun-v2 ${ROOT_MOUNT_DIR}/opt/kontain/shim/containerd-shim-krun-v2
      chmod +x ${ROOT_MOUNT_DIR}/opt/kontain/shim/containerd-shim-krun-v2
      chroot ${ROOT_MOUNT_DIR} ln -sf /opt/kontain/shim/containerd-shim-krun-v2 /usr/bin/containerd-shim-krun-v2

      chmod +x ${ROOT_MOUNT_DIR}/kontain-artifacts/kkm.run

      sleep 2
      chroot ${ROOT_MOUNT_DIR} /kontain-artifacts/kkm.run -- --force-install

      sleep 2
      lsmod |grep kkm
    }
kind: ConfigMap
metadata:
  labels:
    app: kontain-init
  name: kontain-install-lib
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kontain-init
  name: kontain-node-initializer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kontain-init
  template:
    metadata:
      labels:
        app: kontain-init
        name: kontain-node-initializer
    spec:
      containers:
      - command:
        - /scripts/entrypoint.sh
        env:
        - name: ROOT_MOUNT_DIR
          value: /root
        - name: CONTAINERD_CFG_DIR
          value: /etc/containerd
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: centos:7
        name: node-initializer
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /root
          name: root-mount
        - mountPath: /scripts-lib
          name: lib-entrypoint
        - mountPath: /scripts
          name: entrypoint
        - mountPath: /etc/crio/
          name: crio-conf
        - mountPath: /etc/containerd/
          name: containerd-conf
        - mountPath: /var/run/dbus
          name: dbus
        - mountPath: /run/systemd
          name: systemd
      volumes:
      - hostPath:
          path: /
        name: root-mount
      - configMap:
          defaultMode: 484
          name: kontain-install-entrypoint
        name: entrypoint
      - configMap:
          defaultMode: 484
          name: kontain-install-lib
        name: lib-entrypoint
      - hostPath:
          path: /etc/crio/
        name: crio-conf
      - hostPath:
          path: /etc/containerd/
        name: containerd-conf
      - hostPath:
          path: /var/run/dbus
        name: dbus
      - hostPath:
          path: /run/systemd
        name: systemd
  updateStrategy:
    type: RollingUpdate
---
apiVersion: node.k8s.io/v1
handler: krun
kind: RuntimeClass
metadata:
  name: kontain
