name: Check Runner environment
on: # push
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install tools
        run: |
          set -xe
          # ls /dev/kvm
          lscpu
          echo $USER
          echo $HOME
          docker --version
          docker run hello-world